import { useState } from "react";
import { ArrowUpRight, BellRing, CheckCheck, CircleAlert, Filter } from "lucide-react";
import { toast } from "sonner";
import DashboardLayout from "@/components/DashboardLayout";
import { alerts } from "@/data/controlRoomData";

export default function Alerts() {
  const [acknowledged, setAcknowledged] = useState<string[]>([]);
  return <DashboardLayout eyebrow="CHENNAI CITY / OPERATIONAL NOTICES" title="Alert Centre"><section className="alert-banner"><div><span className="section-label">Open fault notifications</span><h2>Three notices require a documented operational response.</h2><p>Alerts can be acknowledged, assigned for field work, or linked directly to a ticket.</p></div><div><BellRing size={24} /><strong>{alerts.length}</strong><span>Open notices</span></div></section><section className="ticket-toolbar"><div className="filter-pills"><button className="active">Open</button><button>High</button><button>Watch</button><button>All</button></div><button className="secondary-action"><Filter size={15} /> Filter by zone</button></section><section className="alert-list">{alerts.map((alert) => { const done = acknowledged.includes(alert.id); return <article key={alert.id} className="alert-item"><i className={alert.severity} /><div className="alert-icon"><CircleAlert size={19} /></div><div className="alert-copy"><span className="section-label">{alert.id} · {alert.category} region</span><h3>{alert.title}</h3><p>{alert.detail}</p><small>{alert.transformerId} · raised {alert.raisedAt}</small></div><span className={`severity-chip ${alert.severity}`}>{alert.severity}</span><div className="alert-actions"><button className="secondary-action" disabled={done} onClick={() => { setAcknowledged((items) => [...items, alert.id]); toast.success("Alert acknowledged", { description: `${alert.id} is now recorded in the operator trail.` }); }}><CheckCheck size={15} /> {done ? "Acknowledged" : "Acknowledge"}</button><button className="row-action" onClick={() => toast.info("Ticket link ready", { description: "Use the Ticket Desk to create or connect a work item." })}><ArrowUpRight size={16} /></button></div></article>; })}</section></DashboardLayout>;
}
