import { useMemo, useState } from "react";
import { ArrowUpRight, Building2, CalendarClock, CircleAlert, Gauge, HousePlus, Landmark, TrendingUp, Wrench } from "lucide-react";
import { useLocation } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";
import { cities, cityLoadAnalysis, getCity, getZone, type LoadAction, type ZoneLoadAnalysis } from "@/data/controlRoomData";

const years = ["2021", "2022", "2023", "2024", "2025", "2026F", "2027F", "2028F", "2029F"];
const priorityRank = { Immediate: 0, Plan: 1, Monitor: 2 };
const actionIcon: Record<LoadAction, typeof CalendarClock> = { "Capacity survey": CalendarClock, "Load balancing": Gauge, "Feeder augmentation": Landmark, "Transformer upgrade": Wrench };

function points(values: number[], maximum: number, startX: number, step: number) {
  return values.map((value, index) => `${startX + index * step},${126 - (value / maximum) * 108}`).join(" ");
}

function ZoneTrend({ item }: { item: ZoneLoadAnalysis }) {
  const combined = [...item.demandHistory, ...item.demandForecast];
  const maximum = Math.max(item.sanctionedKva + 80, ...combined) * 1.05;
  const historic = points(item.demandHistory, maximum, 12, 42);
  const forecast = points([item.demandHistory.at(-1)!, ...item.demandForecast], maximum, 180, 42);
  const capacityBottom = `${(item.sanctionedKva / maximum) * 100}%`;
  return <div className="load-chart"><div className="chart-y"><span>{Math.round(maximum)}</span><span>{Math.round(maximum * .66)}</span><span>{Math.round(maximum * .33)}</span><span>0</span></div><div className="chart-stage"><div className="capacity-line" style={{ bottom: capacityBottom }}><span>Sanctioned capacity · {item.sanctionedKva} kVA</span></div><svg viewBox="0 0 360 140" preserveAspectRatio="none" aria-label="Zone demand trend"><polyline className="historic-line" points={historic} /><polyline className="forecast-line" points={forecast} /></svg><div className="chart-years">{years.map((year, index) => <span className={index > 4 ? "forecast" : ""} key={year}>{year}</span>)}</div></div></div>;
}

export default function LoadAnalysis() {
  const [, setLocation] = useLocation(); const requestedCity = new URLSearchParams(window.location.search).get("city"); const [cityId, setCityId] = useState(requestedCity === "coimbatore" ? "coimbatore" : "chennai"); const city = getCity(cityId); const entries = cityLoadAnalysis(cityId); const [selectedId, setSelectedId] = useState((requestedCity === "coimbatore" ? cityLoadAnalysis("coimbatore") : cityLoadAnalysis("chennai"))[0].zoneId);
  const selected = entries.find((entry) => entry.zoneId === selectedId) ?? entries[0]; const selectedZone = getZone(selected.zoneId);
  const totalCapacity = entries.reduce((sum, entry) => sum + entry.sanctionedKva, 0); const currentPeak = entries.reduce((sum, entry) => sum + entry.demandHistory.at(-1)!, 0); const projectedPeak = entries.reduce((sum, entry) => sum + entry.demandForecast[1], 0); const immediate = entries.filter((entry) => entry.priority === "Immediate");
  const annualGrowth = useMemo(() => { const start = entries.reduce((sum, entry) => sum + entry.demandHistory[0], 0); return Math.round(((currentPeak / start) ** (1 / 4) - 1) * 100); }, [currentPeak, entries]);
  const chooseCity = (id: string) => { setCityId(id); setSelectedId(cityLoadAnalysis(id)[0].zoneId); setLocation(id === "chennai" ? "/load-analysis" : `/load-analysis?city=${id}`); };
  return <DashboardLayout eyebrow={`${city.name.toUpperCase()} CITY / CAPACITY DESK`} title="Load Analysis">
    <section className="load-hero"><div><span className="section-label">Zone capacity planning</span><h2>See rising demand before a transformer becomes insufficient.</h2><p>Illustrative planning signals combine yearly household, apartment and local-use growth with sanctioned transformer capacity to trigger early government action.</p></div><label className="city-picker"><Building2 size={17} /><span>Planning city</span><select value={cityId} onChange={(event) => chooseCity(event.target.value)}>{cities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></section>
    <section className="planning-ribbon"><span><i /> Demonstration planning model</span><p>Population and building-growth indicators are illustrative; use the workflow to determine survey, balancing, augmentation or upgrade priorities.</p></section>
    <section className="capacity-corridor"><span className="section-label">Capacity planning geography</span><div className="corridor-line">{entries.map((entry, index) => <button key={entry.zoneId} onClick={() => setSelectedId(entry.zoneId)} className={selectedId === entry.zoneId ? "selected" : ""}><i className={entry.priority.toLowerCase()} /><strong>{getZone(entry.zoneId).name}</strong><small>{getZone(entry.zoneId).note}</small>{index < entries.length - 1 && <b aria-hidden="true" />}</button>)}</div><em>{city.name} growth corridors · map-led demand planning</em></section>
    <section className="load-kpi-strip"><article><span>Current zonal peak</span><strong>{currentPeak} <small>kVA</small></strong><b>{annualGrowth}% annual growth</b></article><article><span>Available sanctioned capacity</span><strong>{totalCapacity} <small>kVA</small></strong><b>{Math.round(((totalCapacity - currentPeak) / totalCapacity) * 100)}% city headroom</b></article><article className={immediate.length ? "at-risk" : ""}><span>Priority intervention</span><strong>{String(immediate.length).padStart(2, "0")}</strong><b>{immediate.length ? "capacity upgrades due" : "No immediate deficit"}</b></article><article><span>2027 forecast</span><strong>{projectedPeak} <small>kVA</small></strong><b>{projectedPeak > totalCapacity ? "forecast exceeds capacity" : "within present capacity"}</b></article></section>
    <section className="load-workspace"><article className="load-plot-card"><header><div><span className="section-label">Selected zone trend</span><h3>{selectedZone.name} demand against capacity</h3></div><label className="load-zone-selector"><span>{selectedZone.code}</span><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{entries.map((entry) => <option key={entry.zoneId} value={entry.zoneId}>{getZone(entry.zoneId).name}</option>)}</select></label></header><ZoneTrend item={selected} /><footer><span><i className="historic" /> Measured annual peak</span><span><i className="forecast" /> Forecast demand</span><span><i className="capacity" /> Sanctioned capacity</span></footer></article><aside className="load-callout"><span className="section-label">Planning trigger</span><div className={`priority-stamp ${selected.priority.toLowerCase()}`}>{selected.priority}</div><h3>{selected.action}</h3><p>{selected.rationale}</p><dl><div><dt>Capacity headroom</dt><dd>{selected.headroom}%</dd></div><div><dt>Projected insufficiency</dt><dd>{selected.horizon}</dd></div><div><dt>Household growth</dt><dd>{selected.householdGrowth}</dd></div><div><dt>Apartment growth</dt><dd>{selected.apartmentGrowth}</dd></div><div><dt>Commercial growth</dt><dd>{selected.commercialGrowth}</dd></div></dl><button className="primary-action compact"><CircleAlert size={16} /> Open planning note</button></aside></section>
    <section className="load-bottom"><article className="capacity-register"><header><div><span className="section-label">Zone capacity register</span><h3>Where the next load will land</h3></div><span className="register-note"><TrendingUp size={14} /> 2025 measured / 2027 forecast</span></header><div className="capacity-table"><div className="capacity-head"><span>Zone</span><span>Capacity</span><span>2025 peak</span><span>2027 forecast</span><span>Headroom</span><span>Action</span></div>{entries.map((entry) => { const zone = getZone(entry.zoneId); const Icon = actionIcon[entry.action]; return <button key={entry.zoneId} onClick={() => setSelectedId(entry.zoneId)} className={selectedId === entry.zoneId ? "selected" : ""}><span><b>{zone.name}</b><small>{zone.note}</small></span><strong>{entry.sanctionedKva} kVA</strong><strong>{entry.demandHistory.at(-1)} kVA</strong><strong className={entry.demandForecast[1] > entry.sanctionedKva ? "over-capacity" : ""}>{entry.demandForecast[1]} kVA</strong><strong className={entry.headroom < 10 ? "low-headroom" : ""}>{entry.headroom}%</strong><em className={entry.priority.toLowerCase()}><Icon size={14} /> {entry.action}</em></button>; })}</div></article><aside className="action-register"><header><span className="section-label">Government action register</span><h3>Prioritise field and capital decisions</h3></header>{[...entries].sort((a, b) => priorityRank[a.priority] - priorityRank[b.priority]).map((entry) => <div key={entry.zoneId}><span className={entry.priority.toLowerCase()}>{entry.priority}</span><div><strong>{getZone(entry.zoneId).name}</strong><small>{entry.action} · {entry.horizon}</small></div><ArrowUpRight size={16} /></div>)}<footer><HousePlus size={16} /> Review survey returns before sanctioning additional transformer capacity.</footer></aside></section>
  </DashboardLayout>;
}
