import { useCallback, useState } from "react";
import { Activity, ArrowUpRight, Building2, MapPinned, RadioTower, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";
import CityMap from "@/components/CityMap";
import { cities, cityZones, getTransformer, getZone, zoneTransformers, type Transformer } from "@/data/controlRoomData";

export default function Zones() {
  const [cityId, setCityId] = useState("chennai"); const [zoneId, setZoneId] = useState("avadi");
  const activeZones = cityZones(cityId); const zone = getZone(zoneId); const [selected, setSelected] = useState<Transformer>(getTransformer("AVD-TX-027"));
  const selectCity = (id: string) => { const nextZone = cityZones(id)[0]; setCityId(id); setZoneId(nextZone.id); setSelected(zoneTransformers(nextZone.id).find((asset) => asset.issue) ?? zoneTransformers(nextZone.id)[0]); };
  const selectZone = (id: string) => { setZoneId(id); setSelected(zoneTransformers(id).find((asset) => asset.issue) ?? zoneTransformers(id)[0]); };
  const selectAsset = useCallback((asset: Transformer) => setSelected(asset), []);
  return <DashboardLayout eyebrow={`${cityId === "chennai" ? "CHENNAI" : "COIMBATORE"} CITY / ZONE DESK`} title="Zone Monitoring"><section className="page-intro concise"><div><span className="section-label">Zone health and coverage</span><h2>Focus an assigned zone without losing city context.</h2></div><label className="city-picker"><Building2 size={17} /><span>Active city</span><select value={cityId} onChange={(event) => selectCity(event.target.value)}>{cities.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</select></label></section><section className="zone-tabs">{activeZones.map((item) => <button key={item.id} onClick={() => selectZone(item.id)} className={item.id === zoneId ? "active" : ""}><span>{item.code}</span><strong>{item.name}</strong><small>{item.transformerCount} transformers · {item.serviceArea}</small><b>{item.activeAlerts} open notice{item.activeAlerts === 1 ? "" : "s"}</b></button>)}</section><section className="zone-layout"><article className="map-panel"><header><div><span className="section-label">{zone.code}</span><h3>{zone.name} operational map</h3></div><div className="legend"><span><i className="healthy" />Healthy</span><span><i className="watch" />Watch</span><span><i className="fault" />Fault</span></div></header><CityMap zoneId={zoneId} selectedId={selected.id} onSelect={selectAsset} /><footer><span><MapPinned size={15} /> {zone.serviceArea} coverage</span><span><ShieldCheck size={15} /> {zone.healthy} normal assets</span><span><RadioTower size={15} /> 97.8% telemetry</span></footer></article><aside className="zone-inspector"><span className="section-label">Selected transformer</span><h3>{selected.id}</h3><p>{selected.name}</p><div className="health-gauge"><strong>{selected.health}</strong><span>health score</span></div><dl><div><dt>Service coverage</dt><dd>{selected.coverage}</dd></div><div><dt>Last telemetry</dt><dd>{selected.lastUpdate}</dd></div><div><dt>Heartbeat</dt><dd>{selected.heartbeat}</dd></div></dl><Link href={`/transformers?asset=${selected.id}`} className="inline-link">View transformer insight <ArrowUpRight size={15} /></Link></aside></section><section className="section-card transformer-register"><header><div><span className="section-label">Zone transformer register</span><h3>{zone.name} asset health</h3></div><span className="register-note"><Activity size={14} /> Live operational view</span></header><div className="register-grid">{zoneTransformers(zoneId).map((asset) => <button key={asset.id} className={selected.id === asset.id ? "selected" : ""} onClick={() => setSelected(asset)}><i className={asset.state} /><span><strong>{asset.id}</strong><small>{asset.name}</small></span><b>{asset.health}%</b><small>{asset.coverage}</small></button>)}</div></section></DashboardLayout>;
}
